<a href="https://colab.research.google.com/github/JhonFiUNFV/python_prep/blob/master/ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clonamos el repositorio para obtener los dataSet

In [1]:
!git clone https://github.com/joanby/deeplearning-az.git

Cloning into 'deeplearning-az'...
remote: Enumerating objects: 10196, done.
remote: Counting objects: 100% (100/100), done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 10196 (delta 52), reused 78 (delta 40), pack-reused 10096
Receiving objects: 100% (10196/10196), 281.16 MiB | 28.84 MiB/s, done.
Resolving deltas: 100% (77/77), done.
Checking out files: 100% (10119/10119), done.


# Damos acceso a nuestro Drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Test it

In [3]:
!ls '/content/drive/My Drive' 

'2. Intermedio'
 Canva
'CFA - LEVEL II - TANDEM FINANCE'
 Classroom
'Colab Notebooks'
 constancia_empleo3.pdf
 Curso_Proyectos_InviertePE
 Data
'Data (1).xlsx'
 Data.gsheet
 Data.xlsx
 deeplearning-az
 GRUPOS_PY.gsheet
'informe5 (1).gsheet'
 informe5.gsheet
'Investigación UX - JHON VIDAL FIGUEROA CÉSPEDES.gsheet'
'JHON VIDAL FIGUEROA CÉSPEDES.pdf'
 LeWagon
 machinelearning-az
 Master.xlsx
 ModuloII_FundamentosdeMachineLearning
 ModuloIV_ManejodeBasedeDatos
 Operacionalización_tesis.gsheet
 ProgramadeEspecializacionenDataScience
 PROYECTO_CONSTRUCCION.docx
'PROYECTO GRUPO 01.pptx'
 python-ml
'QUANT 2021'
 rar
'SEMINARIO DE ADM DE RIESGO EN BANCA'
'Sesión 2-20220320T150758Z-001.zip'
 tensorflow
'Teoria Económica y Finanzas'
'TESIS JHON FIGUEROA'
 Worksheet.xlsx


# Google colab tools

In [4]:
from google.colab import files # Para manejar los archivos y, por ejemplo, exportar a su navegador
import glob # Para manejar los archivos y, por ejemplo, exportar a su navegador
from google.colab import drive # Montar tu Google drive

# Instalar dependendias

In [5]:
!pip install sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# Instalar Theano

In [6]:
!pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning git://github.com/Theano/Theano.git to /tmp/pip-req-build-06cu4601
  Running command git clone -q git://github.com/Theano/Theano.git /tmp/pip-req-build-06cu4601
  fatal: unable to connect to github.com:
  github.com[0: 140.82.113.3]: errno=Connection timed out

ERROR: Command errored out with exit status 128: git clone -q git://github.com/Theano/Theano.git /tmp/pip-req-build-06cu4601 Check the logs for full command output.


# Instalar Tensorflow y Keras


In [7]:
!pip install keras
!pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# Redes Neuronales Artificales

# Cómo importar las librerías


In [8]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importar el data set


In [9]:
dataset = pd.read_csv('/content/deeplearning-az/datasets/Part 1 - Artificial Neural Networks (ANN)/Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

# Parte 1 - Pre procesado de datos

# Codificar datos categóricos

In [10]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [1])],   
    remainder='passthrough'                        
)
X = onehotencoder.fit_transform(X)
X = X[:, 1:]

In [11]:
X

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

# Dividir el data set en conjunto de entrenamiento y conjunto de testing

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Escalado de variables

In [13]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

# Parte 2 - Construir la RNA

# Importar Keras y librerías adicionales


In [33]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

# Inicializar la RNA

In [15]:
classifier = Sequential()

# Añadir las capas de entrada y primera capa oculta


In [35]:
classifier.add(Dense(units = 6, kernel_initializer = "uniform",  
                     activation = "relu", input_dim = 11))
#classifier.add(Dropout(p = 0.1)) # Quitar el sobreajuste a 0.5

AttributeError: ignored

# Añadir la segunda capa oculta

In [17]:
classifier.add(Dense(units = 6, kernel_initializer = "uniform",  activation = "relu"))

# Añadir la capa de salida

In [18]:
classifier.add(Dense(units = 1, kernel_initializer = "uniform",  activation = "sigmoid"))

# Compilar la RNA

In [19]:
classifier.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])

# Ajustamos la RNA al Conjunto de Entrenamiento

In [20]:
classifier.fit(X_train, y_train,  batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 9s 4ms/step - loss: 0.4768 - accuracy: 0.7960
Epoch 2/100
800/800 [==============================] - 3s 4ms/step - loss: 0.4274 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 3s 4ms/step - loss: 0.4220 - accuracy: 0.7997
Epoch 4/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4184 - accuracy: 0.8207
Epoch 5/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4162 - accuracy: 0.8265
Epoch 6/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4142 - accuracy: 0.8296
Epoch 7/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4125 - accuracy: 0.8311
Epoch 8/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4116 - accuracy: 0.8310
Epoch 9/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4107 - accuracy: 0.8328
Epoch 10/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4096 - accura

In [23]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

# Parte 3 - Evaluar el modelo y calcular predicciones finales

# Predicción de los resultados con el Conjunto de Testing

In [22]:
y_pred  = classifier.predict(X_test)
y_pred = (y_pred>0.5)

# Elaborar una matriz de confusión

In [24]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [25]:
cm

array([[1549,   46],
       [ 268,  137]])

In [26]:
(1546 + 143) / 2000

0.8445

## Parte 4 - Evaluar, mejorar y Ajustar la RNA


### Evaluar la **RNA**


In [27]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [28]:
def build_classifier():
  # Inicializar la RNA
  classifier = Sequential()
  # Añadir las capas de entrada y primera capa oculta
  classifier.add(Dense(units = 6, kernel_initializer = "uniform", activation = "relu", input_dim = 11))
  # Añadir la segunda capa oculta
  classifier.add(Dense(units = 6, kernel_initializer = "uniform", activation = "relu"))
  # Añadir la capa de salida
  classifier.add(Dense(units = 1, kernel_initializer = "uniform", activation = "sigmoid"))
  # Compliar la RNA
  classifier.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])
  # Devolver la clasificación
  return classifier

In [29]:
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, nb_epoch = 100)
accuracies = cross_val_score(estimator=classifier, X = X_train, y = y_train, cv = 10, n_jobs=-1, verbose = 1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  """Entry point for launching an IPython kernel.
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  10 out of  10 | elapsed:   25.6s finished


In [30]:
accuracies

array([0.78625   , 0.79000002, 0.80000001, 0.78250003, 0.81625003,
       0.81      , 0.78750002, 0.79374999, 0.79874998, 0.79500002])

In [32]:
mean = accuracies.mean()
variance = accuracies.std()
print(mean)
print(variance)

0.7960000097751617
0.010105690527913859


### Mejorar la RNA

#### Regularización de Dropout para evitar el *overfitting*


### Ajustar la *RNA*


In [36]:
from sklearn.model_selection import GridSearchCV

In [37]:
def build_classifier(optimizer):
  classifier = Sequential()
  classifier.add(Dense(units = 6, kernel_initializer = "uniform",  activation = "relu", input_dim = 11))
  classifier.add(Dense(units = 6, kernel_initializer = "uniform",  activation = "relu"))
  classifier.add(Dense(units = 1, kernel_initializer = "uniform",  activation = "sigmoid"))
  classifier.compile(optimizer = optimizer, loss = "binary_crossentropy", metrics = ["accuracy"])
  return classifier


In [38]:
classifier = KerasClassifier(build_fn = build_classifier)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  """Entry point for launching an IPython kernel.


In [39]:
parameters = {
    'batch_size' : [25,32],
    'nb_epoch' : [100, 500], 
    'optimizer' : ['adam', 'rmsprop']
}

In [40]:
grid_search = GridSearchCV(estimator = classifier, 
                           param_grid = parameters, 
                           scoring = 'accuracy', 
                           cv = 10)
grid_search = grid_search.fit(X_train, y_train)

best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

320/320 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7959
