<a href="https://colab.research.google.com/github/JhonFiUNFV/python_prep/blob/master/T4_4_Linear_Regression_SciKit_Learn_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://colab.research.google.com/github/joanby/python-ml-course/blob/master/notebooks/T4%20-%204%20-%20Linear%20Regression%20-%20SciKit-Learn-Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clonamos el repositorio para obtener los dataSet

In [ ]:
!git clone https://github.com/joanby/python-ml-course.git

# Damos acceso a nuestro Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
# Test it
!ls '/content/drive/My Drive' 

In [ ]:
from google.colab import files # Para manejar los archivos y, por ejemplo, exportar a su navegador
import glob # Para manejar los archivos y, por ejemplo, exportar a su navegador
from google.colab import drive # Montar tu Google drive

# Regresión lineal en Python
## El paquete scikit-learn para regresión lineal y la selección de rasgos

In [ ]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv("/content/python-ml-course/datasets/ads/Advertising.csv")

In [ ]:
feature_cols = ["TV", "Radio", "Newspaper"]

In [ ]:
X = data[feature_cols]
Y = data["Sales"]

In [ ]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, n_features_to_select=2, step=1)
selector = selector.fit(X,Y)

In [ ]:
selector.support_

array([ True,  True, False])

In [ ]:
selector.ranking_

array([1, 1, 2])

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
X_pred = X[["TV", "Radio"]]

In [ ]:
lm = LinearRegression()
lm.fit(X_pred, Y)

LinearRegression()

In [ ]:
lm.intercept_

2.921099912405138

In [ ]:
lm.coef_

array([0.04575482, 0.18799423])

In [ ]:
lm.score(X_pred, Y)

0.8971942610828956