<a href="https://colab.research.google.com/github/JhonFiUNFV/python_prep/blob/master/T9_1_K_Nearest_Neighbors_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://colab.research.google.com/github/joanby/python-ml-course/blob/master/notebooks/T9%20-%201%20-%20K%20Nearest%20Neighbors-Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clonamos el repositorio para obtener los dataSet

In [1]:
!git clone https://github.com/joanby/python-ml-course.git

Cloning into 'python-ml-course'...
remote: Enumerating objects: 17706, done.
remote: Total 17706 (delta 0), reused 0 (delta 0), pack-reused 17706
Receiving objects: 100% (17706/17706), 523.15 MiB | 18.57 MiB/s, done.
Resolving deltas: 100% (333/333), done.
Checking out files: 100% (16940/16940), done.


# Damos acceso a nuestro Drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')
# Test it
!ls '/content/drive/My Drive' 

Mounted at /content/drive
'2. Intermedio'
 Canva
'CFA - LEVEL II - TANDEM FINANCE'
 Classroom
'Colab Notebooks'
 Curso_Proyectos_InviertePE
'CV_JHON VIDAL FIGUEROA CÉSPEDES .pdf'
 Data
'Data (1).xlsx'
 Data.gsheet
 Data.xlsx
 GRUPOS_PY.gsheet
'informe5 (1).gsheet'
 informe5.gsheet
'Investigación UX - JHON VIDAL FIGUEROA CÉSPEDES.gsheet'
 LeWagon
 Master.xlsx
 ModuloII_FundamentosdeMachineLearning
 ModuloIV_ManejodeBasedeDatos
 ProgramadeEspecializacionenDataScience
 PROYECTO_CONSTRUCCION.docx
'PROYECTO GRUPO 01.pptx'
 python-ml
'QUANT 2021'
'SEMINARIO DE ADM DE RIESGO EN BANCA'
'Sesión 2-20220320T150758Z-001.zip'
'Teoria Económica y Finanzas'
 Worksheet.xlsx


In [3]:
from google.colab import files # Para manejar los archivos y, por ejemplo, exportar a su navegador
import glob # Para manejar los archivos y, por ejemplo, exportar a su navegador
from google.colab import drive # Montar tu Google drive

# K Nearest Neighbors

In [16]:
import numpy as np
from sklearn import preprocessing, neighbors
from sklearn. model_selection import cross_val_score
from sklearn.model_selection import train_test_split
import pandas as pd

In [5]:
df = pd.read_csv("/content/python-ml-course/datasets/cancer/breast-cancer-wisconsin.data.txt", header=None)

df.head()

0   1   2   3   4   5   6   7   8   9   10
0  1000025   5   1   1   1   2   1   3   1   1   2
1  1002945   5   4   4   5   7  10   3   2   1   2
2  1015425   3   1   1   1   2   2   3   1   1   2
3  1016277   6   8   8   1   3   4   3   7   1   2
4  1017023   4   1   1   3   2   1   3   1   1   2

In [6]:
df.describe()

0           1           2           3           4   \
count  6.990000e+02  699.000000  699.000000  699.000000  699.000000   
mean   1.071704e+06    4.417740    3.134478    3.207439    2.806867   
std    6.170957e+05    2.815741    3.051459    2.971913    2.855379   
min    6.163400e+04    1.000000    1.000000    1.000000    1.000000   
25%    8.706885e+05    2.000000    1.000000    1.000000    1.000000   
50%    1.171710e+06    4.000000    1.000000    1.000000    1.000000   
75%    1.238298e+06    6.000000    5.000000    5.000000    4.000000   
max    1.345435e+07   10.000000   10.000000   10.000000   10.000000   

               5           7           8           9           10  
count  699.000000  699.000000  699.000000  699.000000  699.000000  
mean     3.216023    3.437768    2.866953    1.589413    2.689557  
std      2.214300    2.438364    3.053634    1.715078    0.951273  
min      1.000000    1.000000    1.000000    1.000000    2.000000  
25%      2.000000    2.000000    1.000000    1.000000    2.000000  
50%      2.000000    3.000000    1.000000    1.000000    2.000000  
75%      4.000000    5.000000    4.000000    1.000000    4.000000  
max     10.000000   10.000000   10.000000   10.000000    4.000000

In [7]:
df.columns = ["name", "V1", "V2", "V3", "V4", "V5", "V6", "V7", "V8", "V9", "class"]

In [8]:
df.head()

name  V1  V2  V3  V4  V5  V6  V7  V8  V9  class
0  1000025   5   1   1   1   2   1   3   1   1      2
1  1002945   5   4   4   5   7  10   3   2   1      2
2  1015425   3   1   1   1   2   2   3   1   1      2
3  1016277   6   8   8   1   3   4   3   7   1      2
4  1017023   4   1   1   3   2   1   3   1   1      2

In [9]:
df = df.drop(["name"],1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """Entry point for launching an IPython kernel.


In [10]:
df.replace("?", -99999, inplace=True)

In [11]:
Y = df["class"]

In [12]:
X = df[["V1", "V2", "V3", "V4", "V5", "V6", "V7", "V8", "V9"]]

In [13]:
X.head()

V1  V2  V3  V4  V5  V6  V7  V8  V9
0   5   1   1   1   2   1   3   1   1
1   5   4   4   5   7  10   3   2   1
2   3   1   1   1   2   2   3   1   1
3   6   8   8   1   3   4   3   7   1
4   4   1   1   3   2   1   3   1   1

In [14]:
Y.head()

0    2
1    2
2    2
3    2
4    2
Name: class, dtype: int64

## Clasificador de los K vecinos 

In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [18]:
clf = neighbors.KNeighborsClassifier()

In [19]:
clf.fit(X_train, Y_train)

KNeighborsClassifier()

In [20]:
accuracy = clf.score(X_test, Y_test)
accuracy

0.95

# Clasificación sin limpieza

In [21]:
df = pd.read_csv("/content/python-ml-course/datasets/cancer/breast-cancer-wisconsin.data.txt", header=None)
df.replace("?", -99999, inplace=True)
df.columns = ["name", "V1", "V2", "V3", "V4", "V5", "V6", "V7", "V8", "V9", "class"]

Y = df["class"]
X = df[["name", "V1", "V2", "V3", "V4", "V5", "V6", "V7", "V8", "V9"]]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

clf = neighbors.KNeighborsClassifier()
clf.fit(X_train, Y_train)

accuracy = clf.score(X_test, Y_test)
accuracy

0.55

# Clasificar nuevos datos

In [22]:
sample_measure = np.array([5,4,2,1,1,1,2,3,2,1])
print(sample_measure)

[5 4 2 1 1 1 2 3 2 1]


In [23]:
sample_measure = sample_measure.reshape(1,-1)

In [24]:
predict = clf.predict(sample_measure)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"


In [25]:
predict

array([4])

In [26]:
sample_measure2 = np.array([[5,4,2,1,1,1,2,3,2,1], [2,2,4,4,2,2,6,2,4,5]]).reshape(2,-1)

In [27]:
predict = clf.predict(sample_measure2)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"


In [28]:
predict

array([4, 4])