<a href="https://colab.research.google.com/github/JhonFiUNFV/python_prep/blob/master/03_text_distance_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clonamos el repositorio para obtener los dataSet

In [ ]:
!git clone https://github.com/joanby/tensorflow.git

Cloning into 'tensorflow'...
remote: Enumerating objects: 51, done.
remote: Counting objects: 100% (51/51), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 60311 (delta 32), reused 37 (delta 23), pack-reused 60260
Receiving objects: 100% (60311/60311), 442.46 MiB | 14.79 MiB/s, done.
Resolving deltas: 100% (82/82), done.
Checking out files: 100% (60225/60225), done.


# Damos acceso a nuestro Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# Test it

In [ ]:
!ls '/content/drive/My Drive' 

# Google colab tools

In [ ]:
from google.colab import files # Para manejar los archivos y, por ejemplo, exportar a su navegador
import glob # Para manejar los archivos y, por ejemplo, exportar a su navegador
from google.colab import drive # Montar tu Google drive

##Especificando la versión de TensorFlow

Ejecutando "importar tensorflow" importará la versión por defecto (actualmente 2.x). Puedes usar la 1.x ejecutando una celda con la "versión mágica de tensorflow" **antes de ejecutar "importar tensorflow".

### Si no funciona hacer el pip install


In [ ]:
#!pip install tensorflow==1.14
%tensorflow_version 1.x

TensorFlow 1.x selected.


# Importar Tensorflow

In [ ]:
import tensorflow as tf
print(tf.__version__)
import matplotlib.pyplot as plt

1.15.2


In [ ]:
session = tf.Session()

# Distancia de Levenshtein

$x,y\in S$ donde $S$ es el conjunto de Strings, entonces $d(x,y)$ se define como el número de operaciones (ediciones) para convertir la palabra $x$ en la palabra $y$, donde las ediciones posibles de la palabra son:
- insertar un nuevo caracter
- eliminar un caracter de la palabra
- sustituir un caracter por otro

In [ ]:
hypothesis = list('casa')
truth = list('calle')

In [ ]:
h1 = tf.SparseTensor([[0,0,0], [0,0,1], [0,0,2], [0,0,3]],
                    hypothesis, [1,1,1])
t1 = tf.SparseTensor([[0,0,0], [0,0,1], [0,0,2], [0,0,3], [0,0,4]],
                    truth, [1,1,1])

In [ ]:
print(session.run(tf.edit_distance(h1, t1, normalize=False)))

[[3.]]


In [ ]:
print(session.run(tf.edit_distance(h1, t1, normalize=True)))

[[0.6]]


In [ ]:
session.run(h1)

SparseTensorValue(indices=array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 2],
       [0, 0, 3]]), values=array([b'c', b'a', b's', b'a'], dtype=object), dense_shape=array([1, 1, 1]))

In [ ]:
hypothesis2 = list('casacalle')
truth2 = list('callescalles')

In [ ]:
h2 = tf.SparseTensor([[0,0,0], [0,0,1], [0,0,2], [0,0,3], [0,1,0], [0,1,1], [0,1,2],[0,1,3],[0,1,4]],
                    hypothesis2, [1,2,4])
t2 = tf.SparseTensor([[0,0,0], [0,0,1],[0,0,2],[0,0,3],[0,0,4], [0,0,5], 
                      [0,1,0],[0,1,1],[0,1,2],[0,1,3],[0,1,4],[0,1,5]],
                    truth2, [1,2,6])

In [ ]:
print(session.run(tf.edit_distance(h2,t2,normalize=False)))

[[4. 1.]]


In [ ]:
print(session.run(tf.edit_distance(h2,t2,normalize=True)))

[[0.6666667  0.16666667]]


In [ ]:
hypothesis_words = ["casa", "casita", "caseron", "tensor", "python"]
truth_word = "algoritmo"

In [ ]:
num_h_words = len(hypothesis_words)
h_idx = [[xi,0,yi] for xi,x in enumerate(hypothesis_words) for yi,y in enumerate(x)]
h_idx

[[0, 0, 0],
 [0, 0, 1],
 [0, 0, 2],
 [0, 0, 3],
 [1, 0, 0],
 [1, 0, 1],
 [1, 0, 2],
 [1, 0, 3],
 [1, 0, 4],
 [1, 0, 5],
 [2, 0, 0],
 [2, 0, 1],
 [2, 0, 2],
 [2, 0, 3],
 [2, 0, 4],
 [2, 0, 5],
 [2, 0, 6],
 [3, 0, 0],
 [3, 0, 1],
 [3, 0, 2],
 [3, 0, 3],
 [3, 0, 4],
 [3, 0, 5],
 [4, 0, 0],
 [4, 0, 1],
 [4, 0, 2],
 [4, 0, 3],
 [4, 0, 4],
 [4, 0, 5]]

In [ ]:
h_chars = list(''.join(hypothesis_words))
h_chars

['c',
 'a',
 's',
 'a',
 'c',
 'a',
 's',
 'i',
 't',
 'a',
 'c',
 'a',
 's',
 'e',
 'r',
 'o',
 'n',
 't',
 'e',
 'n',
 's',
 'o',
 'r',
 'p',
 'y',
 't',
 'h',
 'o',
 'n']

In [ ]:
h3 = tf.SparseTensor(h_idx, h_chars, [num_h_words, 1, 1])

In [ ]:
truth_word_vect = [truth_word]*num_h_words
truth_word_vect

['algoritmo', 'algoritmo', 'algoritmo', 'algoritmo', 'algoritmo']

In [ ]:
t_idx = [[xi,0,yi] for xi,x in enumerate(truth_word_vect) for yi, y in enumerate(x)]
t_idx

[[0, 0, 0],
 [0, 0, 1],
 [0, 0, 2],
 [0, 0, 3],
 [0, 0, 4],
 [0, 0, 5],
 [0, 0, 6],
 [0, 0, 7],
 [0, 0, 8],
 [1, 0, 0],
 [1, 0, 1],
 [1, 0, 2],
 [1, 0, 3],
 [1, 0, 4],
 [1, 0, 5],
 [1, 0, 6],
 [1, 0, 7],
 [1, 0, 8],
 [2, 0, 0],
 [2, 0, 1],
 [2, 0, 2],
 [2, 0, 3],
 [2, 0, 4],
 [2, 0, 5],
 [2, 0, 6],
 [2, 0, 7],
 [2, 0, 8],
 [3, 0, 0],
 [3, 0, 1],
 [3, 0, 2],
 [3, 0, 3],
 [3, 0, 4],
 [3, 0, 5],
 [3, 0, 6],
 [3, 0, 7],
 [3, 0, 8],
 [4, 0, 0],
 [4, 0, 1],
 [4, 0, 2],
 [4, 0, 3],
 [4, 0, 4],
 [4, 0, 5],
 [4, 0, 6],
 [4, 0, 7],
 [4, 0, 8]]

In [ ]:
t_chars = list(''.join(truth_word_vect))

In [ ]:
t3 = tf.SparseTensor(t_idx, t_chars, [num_h_words,1,1])

In [ ]:
print(session.run(tf.edit_distance(h3, t3, normalize=False)))

[[9.]
 [7.]
 [8.]
 [8.]
 [8.]]


In [ ]:
print(session.run(tf.edit_distance(h3, t3, normalize=True)))

[[1.       ]
 [0.7777778]
 [0.8888889]
 [0.8888889]
 [0.8888889]]


In [ ]:
def create_sparse_words_vect(word_list):
    num_words = len(word_list)
    idx = [[xi,0,yi] for xi,x in enumerate(word_list) for yi, y in enumerate(x)]
    chars = list(''.join(word_list))
    return tf.SparseTensorValue(idx, chars, [num_words, 1, 1])

In [ ]:
hyp_string_sp = create_sparse_words_vect(hypothesis_words)
tr_string_sp = create_sparse_words_vect([truth_word]*len(hypothesis_words))

In [ ]:
h_input = tf.sparse_placeholder(dtype=tf.string)
t_input = tf.sparse_placeholder(dtype=tf.string)

In [ ]:
edit_distance = tf.edit_distance(h_input, t_input, normalize=True)

In [ ]:
feed_dict = {h_input:hyp_string_sp, t_input:tr_string_sp}

In [ ]:
print(session.run(edit_distance, feed_dict=feed_dict))

[[1.       ]
 [0.7777778]
 [0.8888889]
 [0.8888889]
 [0.8888889]]


# Otras distancias para comparar palabras

### Distancia de Hamming
- Número de caracteres iguales en la misma posición. 
- Las dos palabras deben ser de la misma longitud
$$D(s_1,s_2) = \sum_{i=1}^n I_i$$
donde $I_i=1$ si las dos palabras tienen el mismo caracter en la posición i-ésima  y 0 en otro caso

### Distancia del Coseno
- Obtenemos el producto escalar del vector de k-gramas de cada palabra dividida por la norma dos de los mismos
$$D(s_1,s_2) = 1 - \frac{k(s_1)\cdot k(s_2)}{||k(s_1)||||k(s_2)||}$$

### Distancia de Jaccard
- Numero de caracteres en común entre las dos palabras dividido por la unión total de caracteres de ambas palabras
$$D(s_1,s_2) = \frac{|s_1\cap s_2|}{|s_1\cup s_2|}$$